version: '3.8'

services:

  evm-node:
    image: ethereum/client-go:stable
    container_name: evm-node
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - evm-data:/root/.ethereum
    command: >
      --dev
      --http
      --http.addr 0.0.0.0
      --http.api eth,net,web3,personal
      --ws
      --ws.addr 0.0.0.0
      --ws.api eth,net,web3,personal
      --mine
      --miner.threads=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    tty: true
    stdin_open: true

volumes:
  evm-data:
