version: '3.8'

services:

  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil
    ports:
      - "9000:8545"
    command: anvil


  wasmd:
    build:
      context: .
      dockerfile: Dockerfile.wasmd
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
    restart: unless-stopped 

  offchain:
    build:
      context: offchain
    ports:
      - "9002:3000"
    restart: unless-stopped 
    depends_on:
      # - wasmd
      - db

  # TODO Blockscout

  dexplorer:
    build:
      context: .
      dockerfile: Dockerfile.cosmos-explorer
    ports:
      - "9004:3000"
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "9005:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    tty: true
    stdin_open: true

  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "9007:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  evm-data:
  wasmd_data:
  pgdata:
